### ISSUE TITLE
Selecting a component with a signal hook breaks the signal.

### ISSUE THREAD

**Issue by MicahZoltu** [preactjs/preact-devtools#456]
```tsx
export function App() {
	const apple = useSignal(0)
	return <main>
		<div>{apple}</div>
		<button onClick={() => apple.value += 1}>Increment</button>
	</main>
}
```
1. Install Preact DevTools into Brave (I haven't tested other browsers).
2. Run the above app.
3. Open Preact dev tools.
4. Select the `App` component in the `Elements` tab.
5. Notice that you can see the `useSignal` hook in the sidebar.
6. Click the `Increment` button in the app.
7. _Notice that the counter doesn't increase._
8. Click on the `App` component in the `Elements` tab again.
9. _Notice that the counter incremented._
10. _Notice that the `useSignal` hook no longer shows up in the side bar._
11. Click the `Increment` button again.
12. _Notice an error in the console `TypeError: t.setState is not a function`_

```
Uncaught TypeError: t.setState is not a function
    at r.c (index.ts:149:15)
    at t (index.ts:63:13)
    at e.set (index.ts:321:5)
    at Object.onClick [as clickfalse] (App.tsx:24:37)
    at HTMLButtonElement.I (props.js:150:27)
```

**Comment by MicahZoltu** [comment]
I'm *guessing* that the act of clicking on the component in the Elements tab of Preact dev tools results in a hook being installed into the Signal, and that hook installation is somehow broken.  I spent some time trying to debug the issue, but since the debug tools source code is minified it is quite difficult.
